// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package errorcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorRegisterFailed-1000]
	_ = x[ErrorLoginFailed-1001]
	_ = x[ErrorBookmarkBase64Empty-2001]
	_ = x[ErrorBookmarkBase64Error-2002]
	_ = x[ErrorBookmarkBase64WriteFile-2003]
	_ = x[ErrorBookmarkBase64Decode-2004]
}

const (
	_Code_name_0 = "用户注册失败登录失败"
	_Code_name_1 = "书签截图为空解码base64字符串获取图片数据错误将图片数据写入文件编码图片信息"
)

var (
	_Code_index_0 = [...]uint8{0, 18, 30}
	_Code_index_1 = [...]uint8{0, 18, 63, 90, 108}
)

func (i Code) String() string {
	switch {
	case 1000 <= i && i <= 1001:
		i -= 1000
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case 2001 <= i && i <= 2004:
		i -= 2001
		return _Code_name_1[_Code_index_1[i]:_Code_index_1[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
